stages:
  - build
  - test
  - deploy

build:
  tags:
    - mbp_main

  stage: build
  image: docker:20.10.16
  services:
    - docker:dind
    - command:["--tls=false"]

  variables:
    # Define the default Docker image for pipeline jobs
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  before_script:
    # Login to Docker Hub
    - apk add --no-cache docker-compose # Install Docker-Compose to manage services
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD


  script:
    - docker info  # Ensure Docker daemon is reachable
    - echo "Checking Docker Compose version..."
    - docker-compose version
    - echo "Building and starting all services..."
    # starting services from docker-compose
    - docker-compose -f exercise1/docker-compose.yaml up -d --build
    - echo "WAITING FOR ALL SERVICES TO READY UP!!"
    - sleep 15

  only:
    - exercise4  # Perform this step only on the listed branch

# Step 2: Run tests for the Flask application
test:
  tags:
    - mbp_main
  stage: test
  image: python:3.9-bullseye
  before_script:
    - python -m pip install --upgrade pip
    - pip install pytest
    - pip install -r requirements.txt
  script:
    - echo "starting testing......."
    - ls -la
    - pytest exercise1/tests --disable-warnings
  only:
    - exercise4

deploy:
  tags:
    - mbp_main

  stage: deploy
  image: docker:20.10.16
  services:
    - docker:dind
    - command:["--tls=false"]

  before_script:
    # Login to Docker Hub
    - apk add --no-cache docker-compose # Install Docker-Compose to manage services
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

  script:
    - echo "Deploying application for local testing..."
    - docker-compose -f exercise1/docker-compose.yaml up -d
    - echo "Application deployed, Containers running on local machine.."

  only:
    - exercise4
