stages:
  - build
  - test
  - deploy

variables:
  # Define the default Docker image for pipeline jobs
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  # Install Docker-Compose to manage services
  - apk add --no-cache docker-compose


# Step 1: Build the Docker container
build:
  tags:
    - mbp_main

  stage: build
  image: docker:latest

  script:
    # Login to Docker Hub (optional, if pushing to Docker registry)
    - echo "Building and starting all services..."
    # starting services from docker-compose
    - docker-compose -f exercise1/docker-compose.yaml up -d --build
    - echo "WAITING FOR ALL SERVICES TO READY UP!!"
    - sleep 15
    - docker-compose ps #verifying services are running
  only:
    - exercise4  # Perform this step only on the listed branch

# Step 2: Run tests for the Flask application
test:
  stage: test
  image: python:3.9-bullseye
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest tests/ --disable-warnings
  only:
    - exercise4

# Step 3: Deploy the application using Docker Compose on the remote server
deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh
  script:
    # Securely copy the repository files to the remote server
    - ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER "mkdir -p ~/flask-app"
    - scp -o StrictHostKeyChecking=no -r * $DEPLOY_USER@$DEPLOY_SERVER:~/flask-app/

    # Execute Docker Compose on the remote server
    - ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER "
        cd ~/flask-app &&
        docker-compose down &&
        docker-compose build &&
        docker-compose up -d
      "
  only:
    - exercise4