stages:
  - build
  - test
  - deploy

variables:
  # Define the default Docker image for pipeline jobs
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: djsaint03/comp.se.140
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

build:
  tags:
    - mbp_main
  stage: build
  image: docker:20.10.16
  services:
    - docker:dind
    - command:["--tls=false"]

  before_script:
    # Login to Docker Hub
    - apk add --no-cache docker-compose # Install Docker-Compose to manage services
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD


  script:
    - docker info  # Ensure Docker daemon is reachable
    - echo "Checking Docker Compose version..."
    - docker-compose version
    - echo "Building and starting all services..."
    # starting services from docker-compose and pushing to dockerhub repo
    - docker-compose -f exercise1/docker-compose.yaml build
    - docker-compose -f exercise1/docker-compose.yaml push

    - sleep 15

  only:
    - exercise4  # Perform this step only on the listed branch

# Step 2: Run tests for the Flask application
test:
  tags:
    - mbp_main
  stage: test
  image: python:3.9-bullseye
  before_script:
    - python -m pip install --upgrade pip
    - pip install pytest
    - pip install -r requirements.txt
  script:
    - echo "starting testing......."
    - ls -la
    - pytest exercise1/tests --disable-warnings
  only:
    - exercise4

deploy:
  tags:
    - mbp_main

  stage: deploy
  before_script:
    - apk update && apk add --no-cache openssh-client
    - chmod 400 $deployssh_key

  script:
    #deployment via ssh
    - ssh -o StrictHostKeyChecking=no -i $deployssh_key $vmuser@$vm_IP "
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD &&
      docker-compose -f exercise1/docker-compose.yaml down &&
      docker-compose -f exercise1/docker-compose.yaml pull &&
      docker-compose -f exercise1/docker-compose.yaml up -d 
      "
  needs: [ "build" ]  # Wait for build stage
  only:
    - exercise4

